name: Generate Snake

# Define when the action will run (every 6 hours or manually triggered).
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      # Generate the snake contributions graph
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: catsmoker
          gif_output_path: dist/github-contribution-grid-snake.gif
          svg_output_path: dist/github-contribution-grid-snake.svg

      # Display the status of the build for debugging purposes
      - name: Check Git Status
        run: git status

      # Push changes to the repository
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Deploy to GitHub Pages (optional)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
